CREATE DATABASE carepulse;
use carepulse;

CREATE TABLE departments (
    department_id VARCHAR(10) PRIMARY KEY,
    department_name VARCHAR(100),
    bed_capacity INT
);

CREATE TABLE doctors (
    doctor_id VARCHAR(10) PRIMARY KEY,
    doctor_name VARCHAR(100),
    department_id VARCHAR(10),
    specialization VARCHAR(100),
    experience_years INT,
    FOREIGN KEY (department_id) REFERENCES departments(department_id)
);

CREATE TABLE patients (
    patient_id VARCHAR(15) PRIMARY KEY,
    patient_name VARCHAR(100),
    age INT,
    gender VARCHAR(20),
    city VARCHAR(100),
    blood_group VARCHAR(5),
    phone VARCHAR(20),
    insurance_type VARCHAR(50)
);

CREATE TABLE admissions (
    admission_id VARCHAR(15) PRIMARY KEY,
    patient_id VARCHAR(15),
    doctor_id VARCHAR(10),
    department_id VARCHAR(10),
    admission_date DATE,
    discharge_date DATE,
    admission_type VARCHAR(30),
    diagnosis VARCHAR(100),
    waiting_time_minutes INT,
    emergency_priority VARCHAR(30),
    length_of_stay INT,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id),
    FOREIGN KEY (department_id) REFERENCES departments(department_id)
);

CREATE TABLE billing (
    bill_id VARCHAR(15) PRIMARY KEY,
    admission_id VARCHAR(15),
    treatment_cost DECIMAL(12,2),
    medicine_cost DECIMAL(12,2),
    room_charges DECIMAL(12,2),
    total_bill DECIMAL(12,2),
    insurance_covered DECIMAL(12,2),
    payment_status VARCHAR(30),
    FOREIGN KEY (admission_id) REFERENCES admissions(admission_id)
);


SELECT 'departments' AS table_name, COUNT(*) AS row_count
FROM departments

UNION ALL

SELECT 'doctors', COUNT(*)
FROM doctors

UNION ALL

SELECT 'patients', COUNT(*)
FROM patients

UNION ALL

SELECT 'admissions', COUNT(*)
FROM admissions

UNION ALL

SELECT 'billing', COUNT(*)
FROM billing;

-- 1. Which departments have the highest number of admissions?
SELECT
    d.department_name,
    COUNT(a.admission_id) AS total_admissions
FROM admissions a
JOIN departments d
    ON a.department_id = d.department_id
GROUP BY d.department_name
ORDER BY total_admissions DESC;

-- 2. What is the average waiting time for each department?
SELECT
    d.department_name,
    ROUND(AVG(a.waiting_time_minutes), 2) AS avg_waiting_time
FROM admissions a
JOIN departments d
    ON a.department_id = d.department_id
GROUP BY d.department_name
ORDER BY avg_waiting_time DESC;

-- 3. What are the top 10 most common diagnoses?
SELECT
    diagnosis,
    COUNT(*) AS total_cases
FROM admissions
GROUP BY diagnosis
ORDER BY total_cases DESC
LIMIT 10;

-- 4. What is the average length of stay for each department?
SELECT
    d.department_name,
    ROUND(AVG(a.length_of_stay), 2) AS avg_length_of_stay
FROM admissions a
JOIN departments d
    ON a.department_id = d.department_id
GROUP BY d.department_name
ORDER BY avg_length_of_stay DESC;

-- 5. Which doctors have handled the most admissions?
SELECT
    doc.doctor_name,
    d.department_name,
    COUNT(a.admission_id) AS total_admissions
FROM admissions a
JOIN doctors doc
    ON a.doctor_id = doc.doctor_id
JOIN departments d
    ON doc.department_id = d.department_id
GROUP BY doc.doctor_id, doc.doctor_name, d.department_name
ORDER BY total_admissions DESC
LIMIT 10;

-- 6. What is the total revenue generated by each department?
SELECT
    d.department_name,
    ROUND(SUM(b.total_bill), 2) AS total_revenue
FROM billing b
JOIN admissions a
    ON b.admission_id = a.admission_id
JOIN departments d
    ON a.department_id = d.department_id
GROUP BY d.department_name
ORDER BY total_revenue DESC;

-- 7. What percentage of bills are Paid, Pending, or Partially Paid?
SELECT
    payment_status,
    COUNT(*) AS total_bills,
    ROUND(
        COUNT(*) * 100.0 / (SELECT COUNT(*) FROM billing),
        2
    ) AS percentage
FROM billing
GROUP BY payment_status
ORDER BY total_bills DESC;

-- 8. Which departments have above-average waiting time?
SELECT
    d.department_name,
    ROUND(AVG(a.waiting_time_minutes), 2) AS avg_waiting_time
FROM admissions a
JOIN departments d
    ON a.department_id = d.department_id
GROUP BY d.department_name
HAVING AVG(a.waiting_time_minutes) >
       (SELECT AVG(waiting_time_minutes) FROM admissions)
ORDER BY avg_waiting_time DESC;

-- 9. What are the monthly admission trends?
SELECT
    YEAR(admission_date) AS year,
    MONTH(admission_date) AS month,
    COUNT(*) AS total_admissions
FROM admissions
GROUP BY YEAR(admission_date), MONTH(admission_date)
ORDER BY year, month;

-- 10. Rank departments by total revenue
WITH department_revenue AS (
    SELECT
        d.department_name,
        SUM(b.total_bill) AS total_revenue
    FROM billing b
    JOIN admissions a
        ON b.admission_id = a.admission_id
    JOIN departments d
        ON a.department_id = d.department_id
    GROUP BY d.department_name
)
SELECT
    department_name,
    ROUND(total_revenue, 2) AS total_revenue,
    RANK() OVER (ORDER BY total_revenue DESC) AS revenue_rank
FROM department_revenue
ORDER BY revenue_rank;

-- 11. Find the top 3 highest-value bills
SELECT
    b.bill_id,
    b.admission_id,
    ROUND(b.total_bill, 2) AS total_bill,
    b.payment_status
FROM billing b
ORDER BY b.total_bill DESC
LIMIT 3;

-- 12. Which patients have had more than one admission?
SELECT
    p.patient_id,
    p.patient_name,
    COUNT(a.admission_id) AS admission_count
FROM patients p
JOIN admissions a
    ON p.patient_id = a.patient_id
GROUP BY p.patient_id, p.patient_name
HAVING COUNT(a.admission_id) > 1
ORDER BY admission_count DESC;

-- 13. What is the revenue contribution of each payment status?
SELECT
    payment_status,
    COUNT(*) AS bill_count,
    ROUND(SUM(total_bill), 2) AS total_revenue
FROM billing
GROUP BY payment_status
ORDER BY total_revenue DESC;

-- 14. Create a reusable department performance view
CREATE VIEW department_performance AS
SELECT
    d.department_name,
    COUNT(a.admission_id) AS total_admissions,
    ROUND(AVG(a.waiting_time_minutes), 2) AS avg_waiting_time,
    ROUND(AVG(a.length_of_stay), 2) AS avg_length_of_stay,
    ROUND(SUM(b.total_bill), 2) AS total_revenue
FROM departments d
LEFT JOIN admissions a
    ON d.department_id = a.department_id
LEFT JOIN billing b
    ON a.admission_id = b.admission_id
GROUP BY d.department_id, d.department_name;

-- we'll test it with this
SELECT *
FROM department_performance;

-- 15. Rank doctors within their department
WITH doctor_admissions AS (
    SELECT
        doc.doctor_id,
        doc.doctor_name,
        d.department_name,
        COUNT(a.admission_id) AS total_admissions
    FROM doctors doc
    JOIN departments d
        ON doc.department_id = d.department_id
    LEFT JOIN admissions a
        ON doc.doctor_id = a.doctor_id
    GROUP BY
        doc.doctor_id,
        doc.doctor_name,
        d.department_name
)

SELECT
    doctor_name,
    department_name,
    total_admissions,
    RANK() OVER (
        PARTITION BY department_name
        ORDER BY total_admissions DESC
    ) AS department_rank
FROM doctor_admissions
ORDER BY department_name, department_rank;
